# Generated by Django 3.1.3 on 2020-11-30 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slmpd', '0003_auto_20201129_0532'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='crime_neighborhood',
            managers=[
            ],
        ),
    ]
