# Generated by Django 3.1.3 on 2020-12-02 17:10

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('slmpd', '0004_auto_20201130_1748'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='crime_neighborhood',
            managers=[
                ('objectsX', django.db.models.manager.Manager()),
            ],
        ),
    ]
