# Generated by Django 3.1.3 on 2020-12-07 04:42

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('slmpd', '0005_auto_20201202_1710'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='crime_neighborhood',
            managers=[
                ('crimecounts', django.db.models.manager.Manager()),
            ],
        ),
    ]
