# Generated by Django 3.1.3 on 2020-12-07 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slmpd', '0006_auto_20201207_0442'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='crime_neighborhood',
            managers=[
            ],
        ),
    ]
