# Generated by Django 3.1.3 on 2020-12-08 19:39

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('slmpd', '0007_auto_20201207_2343'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='crime_neighborhood',
            managers=[
                ('objects_crimecounts', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='crime_reports',
            managers=[
            ],
        ),
    ]
