# Generated by Django 3.1.3 on 2020-12-17 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slmpd', '0008_auto_20201208_1939'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='crime_neighborhood',
            managers=[
            ],
        ),
    ]
