# Generated by Django 3.1.3 on 2020-12-18 02:22

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('slmpd', '0009_auto_20201217_2359'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='crime_neighborhood',
            managers=[
                ('objects_crimecounts', django.db.models.manager.Manager()),
            ],
        ),
    ]
