# Generated by Django 3.1.3 on 2020-12-24 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slmpd', '0010_auto_20201218_0222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crime_reports',
            options={'ordering': ['crimecode', 'id']},
        ),
    ]
