BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "slmpdata_crime_category" (
	"id"	integer NOT NULL,
	"category"	text NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "slmpdata_crime_neighborhood" (
	"id"	integer NOT NULL,
	"name"	text NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
INSERT INTO "slmpdata_crime_category" ("id","category") VALUES (1,'Homicide');
INSERT INTO "slmpdata_crime_category" ("id","category") VALUES (2,'Rape');
INSERT INTO "slmpdata_crime_category" ("id","category") VALUES (3,'Robbery');
INSERT INTO "slmpdata_crime_category" ("id","category") VALUES (4,'Assault');
INSERT INTO "slmpdata_crime_category" ("id","category") VALUES (5,'Burglary');
INSERT INTO "slmpdata_crime_category" ("id","category") VALUES (6,'Larceny');
INSERT INTO "slmpdata_crime_category" ("id","category") VALUES (7,'Vehicle Theft');
INSERT INTO "slmpdata_crime_category" ("id","category") VALUES (8,'Arson');
INSERT INTO "slmpdata_crime_category" ("id","category") VALUES (9,'Other Assaults');
INSERT INTO "slmpdata_crime_category" ("id","category") VALUES (10,'Forgery');
INSERT INTO "slmpdata_crime_category" ("id","category") VALUES (11,'Fraud');
INSERT INTO "slmpdata_crime_category" ("id","category") VALUES (12,'Embezzlement');
INSERT INTO "slmpdata_crime_category" ("id","category") VALUES (13,'Stolen Property');
INSERT INTO "slmpdata_crime_category" ("id","category") VALUES (14,'Vandalism');
INSERT INTO "slmpdata_crime_category" ("id","category") VALUES (15,'Weapons');
INSERT INTO "slmpdata_crime_category" ("id","category") VALUES (16,'Prostitution and Vice');
INSERT INTO "slmpdata_crime_category" ("id","category") VALUES (17,'Sex Offenses (other)');
INSERT INTO "slmpdata_crime_category" ("id","category") VALUES (18,'Drugs');
INSERT INTO "slmpdata_crime_category" ("id","category") VALUES (19,'Gambling');
INSERT INTO "slmpdata_crime_category" ("id","category") VALUES (20,'Offenses to Family/Child');
INSERT INTO "slmpdata_crime_category" ("id","category") VALUES (21,'DUI');
INSERT INTO "slmpdata_crime_category" ("id","category") VALUES (22,'Liquor Laws');
INSERT INTO "slmpdata_crime_category" ("id","category") VALUES (23,'Drunkenness');
INSERT INTO "slmpdata_crime_category" ("id","category") VALUES (24,'Disorderly Conduct');
INSERT INTO "slmpdata_crime_category" ("id","category") VALUES (25,'Vagrancy');
INSERT INTO "slmpdata_crime_category" ("id","category") VALUES (26,'All Other Crime');
INSERT INTO "slmpdata_crime_category" ("id","category") VALUES (33,'pete');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (1,'Carondelet');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (2,'Patch');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (3,'Holly Hills');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (4,'Boulevard Heights');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (5,'Bevo Mill');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (6,'Princeton Heights');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (7,'Southampton');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (8,'St. Louis Hills');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (9,'Lindenwood Park (neighborhood)');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (10,'Ellendale');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (11,'Clifton Heights');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (12,'The Hill');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (13,'Southwest Garden');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (14,'Northampton');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (15,'Tower Grove South');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (16,'Dutchtown');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (17,'Mount Pleasant');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (18,'Marine Villa');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (19,'Gravois Park (neighborhood)');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (20,'Kosciusko');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (21,'Soulard');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (22,'Benton Park (neighborhood)');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (23,'McKinley Heights');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (24,'Fox Park (neighborhood)');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (25,'Tower Grove East');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (26,'Compton Heights');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (27,'Shaw');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (28,'Botanical Heights');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (29,'Tiffany');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (30,'Benton Park West');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (31,'The Gate District');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (32,'Lafayette Square');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (33,'Peabody Darst Webbe');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (34,'LaSalle Park (neighborhood)');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (35,'Downtown');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (36,'Downtown West');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (37,'Midtown');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (38,'Central West End');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (39,'Forest Park South East');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (40,'Kings Oak');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (41,'Cheltenham');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (42,'Clayton-Tamm');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (43,'Franz Park (neighborhood)');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (44,'Hi-Pointe');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (45,'Wydown Skinker');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (46,'Skinker DeBaliviere');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (47,'DeBaliviere Place');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (48,'West End');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (49,'Visitation Park (neighborhood)');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (50,'Wells Goodfellow');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (51,'Academy');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (52,'Kingsway West');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (53,'Fountain Park (neighborhood)');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (54,'Lewis Place');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (55,'Kingsway East');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (56,'Greater Ville');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (57,'The Ville');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (58,'Vandeventer');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (59,'Jeff Vanderlou');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (60,'St. Louis Place');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (61,'Carr Square');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (62,'Columbus Square');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (63,'Old North St. Louis');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (64,'Near North Riverfront');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (65,'Hyde Park (neighborhood)');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (66,'College Hill');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (67,'Fairground Neighborhood');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (68,'O’Fallon');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (69,'Penrose');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (70,'Mark Twain I-70 Industrial');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (71,'Mark Twain');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (72,'Walnut Park East');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (73,'North Pointe');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (74,'Baden');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (75,'Riverview');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (76,'Walnut Park East');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (77,'Covenant Blu - Grand Center');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (78,'Hamilton Heights');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (79,'North Riverfront');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (80,'Carondelet Park');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (81,'Tower Grove Park');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (82,'Forest Park');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (83,'Fairgrounds Park');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (84,'Penrose Park');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (85,'O’Fallon Park');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (86,'Calvary - Bellefontaine Cemeteries');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (87,'Botanical Garden');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (88,'Wilmore Park');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (89,'Neighborhood Unknown');
INSERT INTO "slmpdata_crime_neighborhood" ("id","name") VALUES (100,'pete');
COMMIT;
